In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("new.csv")
type(data)

pandas.core.frame.DataFrame

In [2]:
data

,GENERIC NAME,CONDITION,SOURCE,COUNT,MONTH,DESTINATION
0,minocycline,Acne,Ernakulam,987.0,February,Idukki
1,sertraline,Depression,Kozhikode,365.0,January,Kannur
2,lisinopril,Hypertension,Kasargod,54.0,December,Ernakulam
3,elvitegravir,AIDS/HIV,Palakkad,32.0,April,Kasargod
4,triamcinolone,Hair Loss,Thiruvananthapuram,65.0,December,Wayanad
5,lidocaine topical,Gastrointestinal,Pathanamthitta,65.0,February,Kasargod
6,emtricitabine,AIDS/HIV,Aleppey,789.0,January,Thiruvananthapuram
7,lisinopril,Hypertension,Kasargod,5.0,March,Thrissur
8,bupropion,Depression,Thiruvananthapuram,654.0,January,Ernakulam
9,diphenhydramine,Cold,Kozhikode,320.0,December,Palakkad
10,minoxidil topical,Hair Loss,Kollam,654.0,January,Aleppey
11,spironolactone,Acne,Thiruvananthapuram,500.0,January,Kollam
12,alvimopan,Gastrointestinal,Kottayam,741.0,December,Ernakulam
13,sertraline,Depression,Kozhikode,65.0,September,Wayanad
14,chlorpheniramine,Cold,Kasargod,654.0,January,Kannur
15,triamcinolone,Hair Loss,Thiruvananthapuram,654.0,December,Kollam
16,elvitegravir,AIDS/HIV,Palakkad,797.0,January,Malappuram
17,lidocaine topical,Gastrointestinal,Pathanamthitta,32.0,October,Kasargod
18,duloxetine,Depression,Kollam,65.0,December,Ernakulam
19,minoxidil topical,Hair Loss,Kollam,6.0,December,Kasargod
20,emtricitabine,AIDS/HIV,Aleppey,987.0,February,Thiruvananthapuram
21,lisinopril,Hypertension,Kasargod,6.0,January,Ernakulam
22,minoxidil topical,Hair Loss,Kollam,654.0,February,Aleppey
23,bupropion,Depression,Thiruvananthapuram,32.0,December,Thrissur
24,spironolactone,Acne,Thiruvananthapuram,125.0,January,Aleppey
25,rizatriptan,Migraine,Palakkad,654.0,January,Kannur
26,elvitegravir,AIDS/HIV,Palakkad,25.0,November,Kozhikode
27,alvimopan,Gastrointestinal,Kottayam,98.0,January,Ernakulam
28,chlorpheniramine,Cold,Kasargod,32.0,December,Thiruvananthapuram
29,rizatriptan,Migraine,Palakkad,65.0,February,Kannur
...,...,...,...,...,...,...
2988,darunavir,AIDS/HIV,Thrissur,21.0,February,Kozhikode
2989,sertraline,Depression,Kozhikode,65.0,December,Thrissur
2990,lidocaine viscous,Gastrointestinal,Thrissur,77.0,January,Palakkad
2991,doxycycline,Acne,Pathanamthitta,789.0,February,Thiruvananthapuram
2992,sumatriptan,Migraine,Malappuram,987.0,February,Thiruvananthapuram
2993,emtricitabine,AIDS/HIV,Aleppey,21.0,January,Ernakulam
2994,eletriptan,Migraine,Wayanad,5.0,December,Thiruvananthapuram
2995,chlorpheniramine,Cold,Kasargod,34.0,July,Kannur
2996,doxycycline,Acne,Pathanamthitta,658.0,August,Thiruvananthapuram
2997,lidocaine viscous,Gastrointestinal,Thrissur,65.0,December,Palakkad
2998,diphenhydramine,Cold,Kozhikode,32.0,January,Thiruvananthapuram
2999,lidocaine viscous,Gastrointestinal,Thrissur,340.0,December,Malappuram
3000,darunavir,AIDS/HIV,Thrissur,21.0,January,Kozhikode
3001,lisinopril,Hypertension,Kasargod,645.0,February,Kannur
3002,bupropion,Depression,Thiruvananthapuram,52.0,December,Kozhikode
3003,sumatriptan,Migraine,Malappuram,5.0,September,Kannur
3004,darunavir,AIDS/HIV,Thrissur,32.0,June,Kasargod
3005,lidocaine viscous,Gastrointestinal,Thrissur,972.0,November,Malappuram
3006,diphenhydramine,Cold,Kozhikode,32.0,December,Aleppey
3007,bupropion,Depression,Thiruvananthapuram,65.0,July,Kasargod
3008,doxycycline,Acne,Pathanamthitta,45.0,September,Kannur
3009,lisinopril,Hypertension,Kasargod,31.0,November,Thiruvananthapuram
3010,diphenhydramine,Cold,Kozhikode,32.0,January,Kollam
3011,bupropion,Depression,Thiruvananthapuram,64.0,March,Kannur
3012,doxycycline,Acne,Pathanamthitta,12.0,January,Kasargod
3013,lidocaine viscous,Gastrointestinal,Thrissur,621.0,October,Malappuram
3014,darunavir,AIDS/HIV,Thrissur,32.0,December,Idukki
3015,eletriptan,Migraine,Wayanad,10.0,June,Idukki
3016,lisinopril,Hypertension,Idukki,645.0,February,Kannur
3017,diphenhydramine,Cold,Kannur,32.0,December,Aleppey

In [3]:
#preprocessing of data

from sklearn.preprocessing import LabelEncoder
processed_data = pd.DataFrame()

#Label Encoder converts into numerical value

lb_make = LabelEncoder()
processed_data["GENERIC NAME"] = lb_make.fit_transform(data["GENERIC NAME"])
#processed_data["GENERIC"] = data["GENERIC NAME"]
#processed_data["CONDITION"] = lb_make.fit_transform(data["CONDITION"])
#processed_data["CONDITIO"] = data["CONDITION"]
processed_data["SOURCE"] = lb_make.fit_transform(data["SOURCE"])
#processed_data["src"] = data["SOURCE"]
#processed_data["cnt"] = data["COUNT"]
processed_data["COUNT"] = lb_make.fit_transform(data["COUNT"])

processed_data["MONTH"] = lb_make.fit_transform(data["MONTH"])
#processed_data["Mon"] = data["MONTH"]
processed_data["DESTINATION"] = lb_make.fit_transform(data["DESTINATION"])
#processed_data["DESTINATIO"] = data["DESTINATION"]

In [4]:
processed_data


#pd.set_option('display.height', 2400)
#pd.set_option('display.max_rows', 2400)

      GENERIC NAME  SOURCE  COUNT  MONTH  DESTINATION
0               15       1    112      3            2
1               18       7     68      4            3
2               13       4     30      2            1
3                9       9     20      0            4
4               22      11     38      2           13
5               11      10     38      3            4
6               10       0    102      4           11
7               13       4      2      7           12
8                1      11     92      4            1
9                5       7     58      2            9
10              16       5     92      4            0
11              19      11     76      4            5
12               0       6     99      2            1
13              18       7     38     11           13
14               2       4     92      4            3
15              22      11     92      2            5
16               9       9    103      4            8
17              11      10     20     10            4
18               7       5     38      2            1
19              16       5      3      2            4
20              10       0    112      3           11
21              13       4      3      4            1
22              16       5     92      3            0
23               1      11     20      2           12
24              19      11     50      4            0
25              17       9     92      4            3
26               9       9     17      9            7
27               0       6     46      4            1
28               2       4     20      2           11
29              17       9     38      3            3
...            ...     ...    ...    ...          ...
2988             4      12     13      3            7
2989            18       7     38      2           12
2990            12      12     44      4            9
2991             6      10    102      3           11
2992            20       8    112      3           11
2993            10       0     13      4            1
2994             8      13      2      2           11
2995             2       4     21      5            3
2996             6      10     95      1           11
2997            12      12     38      2            9
2998             5       7     20      4           11
2999            12      12     63      2            8
3000             4      12     13      4            7
3001            13       4     88      3            3
3002             1      11     29      2            7
3003            20       8      2     11            3
3004             4      12     20      6            4
3005            12      12    109      9            8
3006             5       7     20      2            0
3007             1      11     38      5            4
3008             6      10     26     11            3
3009            13       4     19      9           11
3010             5       7     20      4            5
3011             1      11     37      7            3
3012             6      10      8      4            4
3013            12      12     87     10            8
3014             4      12     20      2            2
3015             8      13      6      6            2
3016            13       2     88      3            3
3017             5       3     20      2            0

[3018 rows x 5 columns]

In [5]:
# to extract the features

#printing the columns

features = processed_data.columns
print(features)

Index(['GENERIC NAME', 'SOURCE', 'COUNT', 'MONTH', 'DESTINATION'], dtype='object')

In [6]:
#printing the last column which is used to predict 

predict_class = data.columns[-1]
predict_class

'DESTINATION'

In [7]:
#print the value to be predicted

predictions = data[predict_class]
predictions

0                   Idukki
1                   Kannur
2                Ernakulam
3                 Kasargod
4                  Wayanad
5                 Kasargod
6       Thiruvananthapuram
7                 Thrissur
8                Ernakulam
9                 Palakkad
10                 Aleppey
11                  Kollam
12               Ernakulam
13                 Wayanad
14                  Kannur
15                  Kollam
16              Malappuram
17                Kasargod
18               Ernakulam
19                Kasargod
20      Thiruvananthapuram
21               Ernakulam
22                 Aleppey
23                Thrissur
24                 Aleppey
25                  Kannur
26               Kozhikode
27               Ernakulam
28      Thiruvananthapuram
29                  Kannur
               ...
2988             Kozhikode
2989              Thrissur
2990              Palakkad
2991    Thiruvananthapuram
2992    Thiruvananthapuram
2993             Ernakulam
2994    Thiruvananthapuram
2995                Kannur
2996    Thiruvananthapuram
2997              Palakkad
2998    Thiruvananthapuram
2999            Malappuram
3000             Kozhikode
3001                Kannur
3002             Kozhikode
3003                Kannur
3004              Kasargod
3005            Malappuram
3006               Aleppey
3007              Kasargod
3008                Kannur
3009    Thiruvananthapuram
3010                Kollam
3011                Kannur
3012              Kasargod
3013            Malappuram
3014                Idukki
3015                Idukki
3016                Kannur
3017               Aleppey
Name: DESTINATION, Length: 3018, dtype: object

In [8]:
#printing the numerical values of DESTINATION to be predicted

prediction_class = processed_data["DESTINATION"]
prediction_class

0        2
1        3
2        1
3        4
4       13
5        4
6       11
7       12
8        1
9        9
10       0
11       5
12       1
13      13
14       3
15       5
16       8
17       4
18       1
19       4
20      11
21       1
22       0
23      12
24       0
25       3
26       7
27       1
28      11
29       3
        ..
2988     7
2989    12
2990     9
2991    11
2992    11
2993     1
2994    11
2995     3
2996    11
2997     9
2998    11
2999     8
3000     7
3001     3
3002     7
3003     3
3004     4
3005     8
3006     0
3007     4
3008     3
3009    11
3010     5
3011     3
3012     4
3013     8
3014     2
3015     2
3016     3
3017     0
Name: DESTINATION, Length: 3018, dtype: int64

In [10]:
features_data = processed_data[["GENERIC NAME","SOURCE","MONTH"]]

#    features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","MONTH"]]

#features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE"]]
features_data

      GENERIC NAME  SOURCE  MONTH
0               15       1      3
1               18       7      4
2               13       4      2
3                9       9      0
4               22      11      2
5               11      10      3
6               10       0      4
7               13       4      7
8                1      11      4
9                5       7      2
10              16       5      4
11              19      11      4
12               0       6      2
13              18       7     11
14               2       4      4
15              22      11      2
16               9       9      4
17              11      10     10
18               7       5      2
19              16       5      2
20              10       0      3
21              13       4      4
22              16       5      3
23               1      11      2
24              19      11      4
25              17       9      4
26               9       9      9
27               0       6      4
28               2       4      2
29              17       9      3
...            ...     ...    ...
2988             4      12      3
2989            18       7      2
2990            12      12      4
2991             6      10      3
2992            20       8      3
2993            10       0      4
2994             8      13      2
2995             2       4      5
2996             6      10      1
2997            12      12      2
2998             5       7      4
2999            12      12      2
3000             4      12      4
3001            13       4      3
3002             1      11      2
3003            20       8     11
3004             4      12      6
3005            12      12      9
3006             5       7      2
3007             1      11      5
3008             6      10     11
3009            13       4      9
3010             5       7      4
3011             1      11      7
3012             6      10      4
3013            12      12     10
3014             4      12      2
3015             8      13      6
3016            13       2      3
3017             5       3      2

[3018 rows x 3 columns]

In [11]:
#training

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features_data,prediction_class,train_size = 0.80,test_size=0.20,random_state = 1)

np.random.seed(0) #to make random numbers predictable

# Show the results of the split
#print "Training set has {} samples.".format(X_train.shape[0])
#print "Testing set has {} samples.".format(X_test.shape[0])

#print(X_train.shape, y_train.shape) 
#print(X_test.shape, y_test.shape) 

print("Training samples")
print(X_train.shape[0])
#print(y_train.shape[0])
print("Testing samples")
print(X_test.shape[0])

Training samples
2414
Testing samples
604

In [12]:
X_train

      GENERIC NAME  SOURCE  MONTH
1754             9       9      1
2043             8      13      4
1050            22      11      9
439             12      12      1
2539            17       9      4
94              22      11      7
2367            20       8      5
1433            13       4      4
2786            16       5      7
268              7       5      2
32              10       0      7
199              3       0      4
2415            21      12      4
228             20       8      4
2246            10       0      5
1628            19      11      1
302              2       4     10
2391             5       7      9
1334             1      11      5
2679            15       1      4
134             21      12      0
1386            10       0     11
825             14       8      1
2207             0       6      5
2641            15       1     10
2836            14       8      1
1900            14       8      9
480              8      13      2
2066            15       1      4
870              3       0      1
...            ...     ...    ...
1031             9       9      9
2025            18       7     11
2189            14       8      0
1110             2       4      8
1888             5       7      9
1527             7       5      2
753              0       6     10
2628            11      10      5
562              2       4      7
2446            18       7      1
668             15       1      4
252             16       5     10
2955            14       8      2
2516            13       4      2
2962            10       0      7
357              8      13      3
1278             0       6      4
1300            18       7      5
1202            17       9      3
2556            13       4      2
2797            16       5      9
129             19      11      0
144             19      11      8
960             18       7      9
2895            10       0     11
2763             5       7      0
905             14       8      5
1096             8      13      0
235              0       6      2
1061            14       8      4

[2414 rows x 3 columns]

In [13]:
y_train

1754     8
2043     5
1050     5
439      8
2539     3
94       4
2367    11
1433     3
2786     1
268      4
32      11
199     11
2415    13
228      1
2246    11
1628     6
302      3
2391     9
1334     1
2679     9
134      9
1386     2
825     12
2207     1
2641     2
2836    12
1900    12
480     11
2066     2
870     11
        ..
1031     7
2025    13
2189    12
1110     3
1888     9
1527     1
753      1
2628     3
562      3
2446    12
668      9
252      0
2955    12
2516     1
2962     1
357      1
1278     3
1300     3
1202    12
2556    12
2797     0
129      3
144      5
960     12
2895     2
2763     3
905     11
1096     5
235      3
1061    12
Name: DESTINATION, Length: 2414, dtype: int64

In [14]:
#applying model

#fitting into KNN

from sklearn import neighbors
from sklearn.model_selection import cross_val_score

knn = neighbors.KNeighborsClassifier(n_neighbors = 3)
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [15]:
cv_scores = cross_val_score(knn, features_data, prediction_class, cv = 10)
cv_scores

array([ 0.54545455,  0.50974026,  0.56721311,  0.51147541,  0.55149502,
        0.55813953,  0.5083612 ,  0.55852843,  0.50675676,  0.58783784])

In [16]:
cv_scores.mean()

0.54050021079816035

In [17]:
#printing confusion matrix

knn.fit(X_train,y_train)
predictions_test = knn.predict(X_test)

predictions_test

array([ 2, 13, 11,  1,  1,  7,  5, 13,  1, 11,  5,  1,  5,  1,  3,  8, 11,
       12,  1,  7,  5,  7,  9,  8,  1,  3,  6,  3, 13,  1,  3,  0,  2,  3,
        3,  8,  1,  9,  3,  3,  1,  3,  7,  1,  1,  3,  3,  3,  3,  2,  2,
       12,  9,  3, 12,  8, 11,  5,  2,  1,  9,  8,  1,  9, 11, 11,  1,  8,
        1,  1, 11,  3,  0,  7,  7,  3,  3,  1, 11, 11,  2,  8,  1,  5, 11,
        9,  1,  3, 13,  1,  5, 12,  1,  1,  2,  9,  1,  1,  7,  3,  3,  9,
        9,  5,  1,  1,  3,  1,  3,  5,  2,  9,  9,  3,  3, 12,  1,  5,  1,
        2,  2,  9,  1,  3, 12,  1,  9,  3,  9,  1,  2,  3,  2,  3,  3,  1,
        2,  2,  5,  9,  5,  5, 11,  3, 13, 12,  9,  1,  3, 13,  1,  2,  5,
        0, 11,  3,  1,  9,  3,  1,  5,  9,  3, 11,  3,  0,  3,  1,  0,  2,
        5,  6,  0, 11,  3,  3,  5,  1,  2,  1,  3,  3,  7,  8,  0,  1,  5,
       11, 11,  1,  5, 11,  5, 11,  5,  0, 13,  3,  9, 11,  2,  8,  9,  5,
        5,  9,  3,  2, 11, 13,  1,  5,  3,  1,  1,  9,  3, 12,  2, 11,  7,
        3,  7,  3,  9,  9, 12,  3,  9,  3,  3, 11,  1,  5,  5,  1,  1,  1,
        3,  5, 11,  3,  1,  8,  7,  8,  9, 11,  2,  3,  1,  1,  5,  2,  1,
       11, 10,  2,  0, 11,  1,  5,  3,  3,  2,  7,  5,  3,  1, 11,  3,  5,
        2,  1,  1,  1,  9,  1,  1,  7, 11,  1,  1,  1, 11,  2, 11,  1,  7,
        1,  9,  1,  2,  2,  2,  1,  5, 11, 11, 11,  2,  5,  9,  2,  1,  3,
        1,  1,  3,  3, 12,  3,  3,  1,  1,  5,  3,  8, 11,  7,  0, 11,  3,
       11,  1,  1,  3,  9, 11,  2,  8,  9,  2,  9,  2,  3,  8,  8,  3,  1,
       11,  5,  9,  1,  9,  1, 13,  1,  0,  8,  1,  2,  3, 12,  1,  3,  1,
        3,  0,  2, 11,  7,  5,  9,  1,  1,  1, 11,  7,  1,  3,  9,  2,  9,
        1,  5, 11,  5,  2,  3,  3,  1,  2,  3,  2,  9,  1,  0, 11,  0,  3,
       12,  7,  1,  3,  9,  3,  3,  7,  8,  3,  7,  9,  1,  7,  1,  1,  9,
        3,  1,  1,  1,  1,  2,  5,  1,  1,  1,  5,  8,  1,  9, 11, 11,  5,
       12,  5,  3,  2,  5,  2,  7,  1,  5,  3,  1,  7,  1, 11,  5,  3,  3,
        1, 10,  1, 13,  2,  9,  1,  3,  2,  5,  1,  0, 12,  8, 11,  7,  5,
        9,  2,  1,  2,  1,  3,  7,  2,  1,  2,  3,  5,  5, 11, 11,  1,  3,
        3,  3,  3,  1,  3,  1,  3, 12,  1,  5,  3,  1,  5, 11,  8,  5,  3,
        5,  9,  5,  3, 11,  1,  1,  5,  9,  9,  1, 11,  5,  1,  3,  3,  2,
        7,  1,  2,  5,  5,  6,  1,  1, 11,  1,  3, 11,  3,  1,  2,  1,  2,
       13, 12,  8,  3,  8,  2,  1,  0,  1,  3,  3,  1,  3, 12,  5,  8,  1,
        3,  1,  1,  8, 11,  9, 12, 11,  8,  9,  9, 12,  5,  2, 11,  2,  1,
        8,  1, 11,  1,  8, 11,  9,  1,  3,  9,  1, 12,  3, 12,  1,  1,  3,
        9,  8,  7,  9,  8,  8, 11,  1, 12,  3,  3,  5,  5,  9,  1, 12, 12,
        1,  1,  3,  9,  0, 10,  0,  5, 11])

In [18]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  

# Model Accuracy: how often is the classifier correct?
print(confusion_matrix(y_test,predictions_test))

[[12  3  0  4  0  1  0  2  0  0  0  0  0  2]
 [ 2 52  7  9  0  5  2  1  0  0  0  3  0  4]
 [ 2  7 25  4  0  0  0  0  0  0  0  0  3  0]
 [ 0 10  7 55  0  2  0  0  2  3  0  5  3  0]
 [ 0  9  1  0  0  3  0  2  0  1  0  4  0  1]
 [ 0 16  1  5  0 26  1  0  0  0  1  3  2  0]
 [ 0  0  1  0  0  0  0  0  0  1  0  0  0  0]
 [ 2  4  1  4  0  6  0 11  1  1  0  0  0  0]
 [ 0  6  0  2  0  4  0  0 22  0  0  0  0  0]
 [ 0  5  5  3  0  1  0  2  0 37  0  0  0  0]
 [ 0  3  2  4  0  4  0  0  0  0  2  0  0  0]
 [ 0 15  2  8  0  3  0  6  5  4  0 39  0  2]
 [ 0  8  2  7  0  3  0  0  0  2  0  5 16  0]
 [ 0  5  2  5  0  5  0  3  0  7  0  1  0  2]]

In [19]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,predictions_test))

Accuracy is 0.495033112583

In [20]:
print(classification_report(y_test,predictions_test))

              precision    recall  f1-score   support

           0       0.67      0.50      0.57        24
           1       0.36      0.61      0.46        85
           2       0.45      0.61      0.52        41
           3       0.50      0.63      0.56        87
           4       0.00      0.00      0.00        21
           5       0.41      0.47      0.44        55
           6       0.00      0.00      0.00         2
           7       0.41      0.37      0.39        30
           8       0.73      0.65      0.69        34
           9       0.66      0.70      0.68        53
          10       0.67      0.13      0.22        15
          11       0.65      0.46      0.54        84
          12       0.67      0.37      0.48        43
          13       0.18      0.07      0.10        30

   micro avg       0.50      0.50      0.50       604
   macro avg       0.45      0.40      0.40       604
weighted avg       0.50      0.50      0.48       604

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
#Create a Gaussian Classifier
gau = GaussianNB()

cvscores_gau = cross_val_score(gau,features_data,prediction_class,cv=10)
cvscores_gau

array([ 0.28246753,  0.27272727,  0.27213115,  0.28196721,  0.23920266,
        0.28239203,  0.26421405,  0.28093645,  0.28040541,  0.23648649])

In [23]:
cvscores_gau.mean()

0.26929302438000574

In [24]:
# Train the model using the training sets
gau.fit(X_train,y_train)

#Predict Output
prediction_gau = gau.predict(X_test) # 0:Overcast, 2:Mild

In [25]:
prediction_gau

array([11,  1,  3,  1,  3,  3,  5,  1,  1,  1,  5,  3,  5,  1,  8,  8, 11,
        3,  1,  3,  5, 11,  1,  8, 11,  3,  1,  5, 11,  5,  8,  3, 11,  3,
        3,  8,  5,  1,  1,  1,  8,  3,  1,  1, 11,  5,  1,  5,  3,  2,  3,
        3,  1,  5,  3,  8,  3,  5, 11,  5,  3,  8,  5,  5, 11, 11,  1,  8,
        8,  3,  8,  3,  3,  1, 11,  1,  3,  8, 11,  3,  2,  8,  1, 11, 11,
        1,  1,  1,  1,  8,  5,  3,  8,  8,  3,  1,  5,  8,  3,  3,  8,  1,
        1,  1,  8,  1,  1,  1,  8,  8, 11,  1,  5,  1,  3,  3,  8,  5,  3,
       11,  8,  1, 11,  1,  3,  5,  5, 11,  1, 11,  3,  5,  2,  5,  8,  8,
        1,  2,  8,  8, 11,  5, 11,  3,  1,  3,  5,  5,  1, 11,  1,  3,  5,
        3, 11, 11,  1,  5,  3, 11,  8,  8,  3, 11,  3,  3,  5,  3,  3,  8,
        5,  1,  3, 11,  1,  5,  8,  8,  3,  3,  3,  1,  1,  8,  3,  3,  1,
       11, 11,  1,  5, 11,  8,  3,  5,  3,  3,  1,  5,  3, 11,  8,  1,  8,
        5,  1,  1, 11, 11,  1,  1,  8,  3,  1,  5,  1,  8,  1, 11,  3, 11,
        1,  1,  1,  1,  1,  3,  3,  1,  5,  8,  3,  8,  5,  5,  1,  3,  5,
        8,  1,  3,  1,  1,  8,  3,  8,  3,  8,  2,  5, 11,  5,  8, 11,  1,
       11,  5,  8,  3, 11,  1,  8,  8,  3, 11, 11,  5,  3,  5,  3,  3,  5,
        1,  1,  8,  8,  5,  1,  1, 11,  3,  1,  3, 11,  1,  8,  3,  5,  3,
        5,  5, 11, 11,  1,  1,  5,  5, 11, 11, 11,  2,  8,  1, 11,  8,  1,
        3,  8,  8, 11,  3,  5,  1,  3,  8,  8,  3,  8, 11,  1,  3,  3,  3,
       11, 11,  3,  1,  1,  3,  3,  8,  1,  1,  8,  8,  3,  8,  8,  3,  1,
        3,  8,  5,  5,  3,  1, 11,  8,  3,  8,  1,  2,  8,  3,  1,  1,  1,
        5,  3,  1, 11,  1,  5,  5,  3,  5,  5,  8, 11,  3,  8,  1,  8,  1,
        8,  8,  3,  5, 11,  3,  1,  1, 11,  8, 11,  3,  1,  3,  1,  5,  3,
        3,  1,  3,  3,  5,  5,  5, 11,  8,  1,  1,  5,  1,  3,  1,  8,  1,
        5,  8, 11,  1,  1,  2,  8,  1,  8,  5,  5,  8,  3,  5, 11,  3,  5,
        1,  8,  5,  8,  5,  1,  1,  3,  1,  3,  1,  1, 11,  3,  5,  3,  8,
        8,  5,  1,  1, 11,  1,  1,  5, 11,  5,  3,  3,  1,  8, 11,  3,  5,
        1, 11, 11, 11,  1,  8,  1,  1, 11,  1,  1,  5,  5, 11, 11,  1,  8,
        1,  3,  5,  8,  8,  8,  3,  3,  1, 11,  1,  1,  5, 11,  8,  5,  3,
        8,  5,  5,  5,  1,  1,  5,  8,  5,  5,  1,  8,  5,  1,  3,  5,  2,
        3,  1,  2,  8,  5,  5,  1,  5,  1,  5,  3, 11,  1,  8, 11,  1,  2,
        1,  3,  8,  3,  8,  1,  1,  5,  1,  3,  8,  1,  1,  3,  5,  8,  5,
        1,  1,  1,  8,  3,  1,  3,  1,  8,  1,  5,  3,  8,  2,  1,  8,  5,
        8,  3,  8,  3,  8, 11,  8,  1,  1,  1,  8,  3,  3,  3,  3,  8,  5,
        1,  8,  1,  3,  8,  8, 11,  5,  3,  3, 11,  5,  5,  1,  1,  3,  3,
        1,  3,  1,  5,  3,  5,  3,  5, 11])

In [26]:
print(confusion_matrix(y_test,prediction_gau))

[[ 0  0  0 14  0  8  0  0  0  0  0  2  0  0]
 [ 0 37  0 18  0 11  0  0 13  0  0  6  0  0]
 [ 0 11  3  7  0  3  0  0  2  0  0 15  0  0]
 [ 0 25  3 28  0 11  0  0  9  0  0 11  0  0]
 [ 0  7  0  3  0  3  0  0  5  0  0  3  0  0]
 [ 0  3  0  7  0 26  0  0 15  0  0  4  0  0]
 [ 0  0  1  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  7  0  6  0  5  0  0  9  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0 34  0  0  0  0  0]
 [ 0 25  3  3  0 18  0  0  3  0  0  1  0  0]
 [ 0  5  0  1  0  6  0  0  0  0  0  3  0  0]
 [ 0 20  2 18  0  1  0  0 18  0  0 25  0  0]
 [ 0 15  0 23  0  0  0  0  2  0  0  3  0  0]
 [ 0  5  0  6  0 13  0  0  2  0  0  4  0  0]]

In [27]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,prediction_gau))

Accuracy is 0.253311258278

In [28]:
print(classification_report(y_test,prediction_gau))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        24
           1       0.23      0.44      0.30        85
           2       0.25      0.07      0.11        41
           3       0.21      0.32      0.25        87
           4       0.00      0.00      0.00        21
           5       0.25      0.47      0.32        55
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00        30
           8       0.30      1.00      0.47        34
           9       0.00      0.00      0.00        53
          10       0.00      0.00      0.00        15
          11       0.31      0.30      0.30        84
          12       0.00      0.00      0.00        43
          13       0.00      0.00      0.00        30

   micro avg       0.25      0.25      0.25       604
   macro avg       0.11      0.19      0.13       604
weighted avg       0.16      0.25      0.18       604

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [29]:
from sklearn import tree

dec = tree.DecisionTreeClassifier()

dec

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [30]:
cv_scores_dec = cross_val_score(dec,features_data,prediction_class,cv=10)
cv_scores_dec

array([ 0.4512987 ,  0.42207792,  0.46557377,  0.39672131,  0.4551495 ,
        0.45847176,  0.41137124,  0.45819398,  0.39189189,  0.44932432])

In [31]:
cv_scores_dec.mean()

0.43600744014098292

In [32]:
dec.fit(X_train, y_train)

prediction_dec = dec.predict(X_test)
prediction_dec

array([ 2, 13, 11,  1,  1,  7, 13, 13,  1, 11,  3,  0,  5,  1,  8,  8,  1,
       11,  1,  2, 13,  7,  9,  8,  1,  3,  6,  3,  7, 13,  5,  0, 13,  3,
        3,  8, 13,  3,  3,  3,  2,  3,  7,  1,  1,  5,  3,  3,  3,  2, 12,
        3,  3,  3, 12,  8, 11,  1,  2,  1,  9,  3, 13,  9, 11, 11,  1,  8,
        2, 12, 11,  3,  0,  1, 13, 12,  3,  1, 11, 11,  6,  8,  1,  1, 11,
        3,  1,  1, 13,  1, 13, 11,  1,  2, 12,  9, 13,  1,  7,  3,  5,  3,
        9,  9,  9, 11,  3,  1,  3,  5, 13,  9,  9,  3,  3, 12,  9,  5,  1,
        2, 12,  9,  1,  1,  3,  1,  9,  3,  9,  1,  0,  3,  6,  3,  3,  1,
        1,  6,  5, 11,  1, 13, 11,  3, 13, 12,  9,  0,  3,  5,  1,  0,  1,
        0, 11,  3,  1, 13,  3,  1,  5, 11,  3, 11,  3,  0,  3,  0,  0, 12,
        5,  6,  0, 11,  1,  3,  5,  1,  0, 12,  3,  1,  7,  8,  0,  1,  9,
       11, 11,  1, 13, 11,  5, 11,  5,  0, 11,  3,  9, 11,  2,  8,  4,  5,
        5,  9,  3,  2, 11, 13, 11,  5,  3,  1,  0,  9,  3,  1,  9, 11, 11,
       12,  7,  3,  9,  3, 12,  3,  9,  3,  8, 11,  1, 13,  5,  1,  1,  1,
        5,  9, 11,  3,  1,  8,  2,  8,  9, 11,  6,  3,  1,  0,  5, 13,  1,
       11,  5, 12,  0, 11,  1,  8,  3,  3,  2,  7,  5,  3,  0, 11,  3,  5,
        1,  1,  2,  1,  9,  1, 11, 13, 11,  1,  1,  1,  4, 12, 11, 13,  7,
       13,  9, 11, 13,  1,  1,  1,  5, 11, 11, 11,  2,  8,  9,  2,  1,  3,
       12,  2,  3,  3, 12,  3,  1,  1,  1,  8,  3,  8, 11,  7,  0, 11,  3,
       11,  1, 12,  3,  9, 11, 12,  8,  9,  9, 11, 11,  2,  8,  8,  3,  1,
       11,  8,  9,  1,  9,  1,  7,  1,  0,  8,  1,  6,  5, 12,  1,  1,  1,
        3,  0,  1, 11,  1,  5, 13,  1,  1,  0, 11,  7,  1,  8,  9, 12,  9,
        1,  5,  3, 13,  9,  3,  3,  1, 13,  5,  9,  9,  1,  0, 11,  5,  3,
       12,  7,  3,  3,  9,  3,  3, 11,  8,  3,  7,  9,  1,  7,  1,  1,  4,
        3,  9, 11,  1,  1,  6,  8,  1,  1, 13,  5,  8, 12, 13, 11, 11, 13,
        3,  8,  3, 11,  5,  9,  7,  1,  9,  3,  1,  1,  1, 11,  5,  3,  3,
        9,  5,  1, 13, 13,  3,  1,  3,  2,  5, 12,  0,  3,  3, 11,  7, 13,
        3,  2,  1, 13, 11,  8,  1,  1,  1,  1,  3,  5, 13, 11, 11,  1,  8,
        3,  3,  3,  1,  5,  1,  3, 12,  1,  1,  3,  1, 13, 11,  8,  5,  3,
        8,  9,  5,  3,  4, 12,  1,  8,  9,  9,  1, 11, 13,  1,  3,  3,  6,
        2,  1,  2,  8, 13,  6,  1,  1, 11,  0,  3,  1,  3,  1,  2,  1,  6,
       13,  3,  8,  3,  3,  9,  1,  5,  1,  2,  3,  1,  3, 12, 13,  8,  1,
       12,  1,  1, 11, 11,  3, 11, 11,  8,  9,  9, 12,  8,  6, 11, 11,  0,
        8,  1, 11,  1,  3, 11, 11,  1,  3,  3,  1, 12,  3, 12, 12,  1,  3,
        9,  8,  7,  9,  8,  8, 11,  1,  3,  3,  3,  5,  5,  9,  1, 11,  3,
       11,  1, 12,  9,  0,  5,  0, 13, 11])

In [33]:
from sklearn.metrics import accuracy_score

#confusion matrix

print(confusion_matrix(y_test,prediction_dec))

[[12  1  0  4  0  2  0  4  0  0  0  0  0  1]
 [ 4 41  1  5  0  7  2  0  0  1  0  6 10  8]
 [ 2  7 12  3  0  0  2  0  0  4  0  7  2  2]
 [ 2 11  1 52  0  5  3  0  3  0  0  5  3  2]
 [ 1  7  2  0  2  1  0  2  0  0  0  3  0  3]
 [ 4 13  0  5  0 16  1  0  4  1  0  3  4  4]
 [ 0  0  0  0  0  0  1  0  0  1  0  0  0  0]
 [ 2  6  1  4  0  3  0  4  4  2  0  3  0  1]
 [ 0  4  0  2  0  2  0  0 23  2  0  1  0  0]
 [ 0  2  0  6  1  0  3  2  1 31  0  2  0  5]
 [ 0  6  0  2  0  2  0  0  0  0  0  0  0  5]
 [ 0 14  6  8  1  1  0  3  5  4  0 38  2  2]
 [ 0 11  0 13  0  2  0  0  0  1  0  5 11  0]
 [ 1  4  0  5  0  0  0  3  0  5  0  4  0  8]]

In [34]:
#accuracy

print("Accuracy is " ,metrics.accuracy_score(y_test,prediction_dec))

Accuracy is  0.415562913907

In [35]:
#giving input 
new=pd.DataFrame([[15,1,112,3]])
new

    0  1    2  3
0  15  1  112  3

In [36]:
test=knn.predict(new)
arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
int(test)

ValueError: query data dimension must match training data dimension

In [37]:
pre_out_knn =arr[int(test)]

NameError: name 'arr' is not defined

In [44]:
print(pre_out_knn)

Idukki

In [45]:
pre_out_gau = gau.predict(new)

In [46]:
print(pre_out_gau)

[11]

In [47]:
pre_out_dec = dec.predict(new)

In [48]:
print(pre_out_dec)

[2]