In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("nocount.csv")
type(data)

pandas.core.frame.DataFrame

In [92]:
data

,GENERIC NAME,CONDITION,SOURCE,MONTH,DESTINATION
0,minocycline,Acne,Ernakulam,February,Idukki
1,sertraline,Depression,Kozhikode,January,Kannur
2,lisinopril,Hypertension,Kasargod,December,Ernakulam
3,elvitegravir,AIDS/HIV,Palakkad,April,Kasargod
4,triamcinolone,Hair Loss,Thiruvananthapuram,December,Wayanad
5,lidocaine topical,Gastrointestinal,Pathanamthitta,February,Kasargod
6,emtricitabine,AIDS/HIV,Aleppey,January,Thiruvananthapuram
7,lisinopril,Hypertension,Kasargod,March,Thrissur
8,bupropion,Depression,Thiruvananthapuram,January,Ernakulam
9,diphenhydramine,Cold,Kozhikode,December,Palakkad
10,minoxidil topical,Hair Loss,Kollam,January,Aleppey
11,spironolactone,Acne,Thiruvananthapuram,January,Kollam
12,alvimopan,Gastrointestinal,Kottayam,December,Ernakulam
13,sertraline,Depression,Kozhikode,September,Wayanad
14,chlorpheniramine,Cold,Kasargod,January,Kannur
15,triamcinolone,Hair Loss,Thiruvananthapuram,December,Kollam
16,elvitegravir,AIDS/HIV,Palakkad,January,Malappuram
17,lidocaine topical,Gastrointestinal,Pathanamthitta,October,Kasargod
18,duloxetine,Depression,Kollam,December,Ernakulam
19,minoxidil topical,Hair Loss,Kollam,December,Kasargod
20,emtricitabine,AIDS/HIV,Aleppey,February,Thiruvananthapuram
21,lisinopril,Hypertension,Kasargod,January,Ernakulam
22,minoxidil topical,Hair Loss,Kollam,February,Aleppey
23,bupropion,Depression,Thiruvananthapuram,December,Thrissur
24,spironolactone,Acne,Thiruvananthapuram,January,Aleppey
25,rizatriptan,Migraine,Palakkad,January,Kannur
26,elvitegravir,AIDS/HIV,Palakkad,November,Kozhikode
27,alvimopan,Gastrointestinal,Kottayam,January,Ernakulam
28,chlorpheniramine,Cold,Kasargod,December,Thiruvananthapuram
29,rizatriptan,Migraine,Palakkad,February,Kannur
...,...,...,...,...,...
24114,darunavir,AIDS/HIV,Thrissur,February,Kozhikode
24115,sertraline,Depression,Kozhikode,December,Thrissur
24116,lidocaine viscous,Gastrointestinal,Thrissur,January,Palakkad
24117,doxycycline,Acne,Pathanamthitta,February,Thiruvananthapuram
24118,sumatriptan,Migraine,Malappuram,February,Thiruvananthapuram
24119,emtricitabine,AIDS/HIV,Aleppey,January,Ernakulam
24120,eletriptan,Migraine,Wayanad,December,Thiruvananthapuram
24121,chlorpheniramine,Cold,Kasargod,July,Kannur
24122,doxycycline,Acne,Pathanamthitta,August,Thiruvananthapuram
24123,lidocaine viscous,Gastrointestinal,Thrissur,December,Palakkad
24124,diphenhydramine,Cold,Kozhikode,January,Thiruvananthapuram
24125,lidocaine viscous,Gastrointestinal,Thrissur,December,Malappuram
24126,darunavir,AIDS/HIV,Thrissur,January,Kozhikode
24127,lisinopril,Hypertension,Kasargod,February,Kannur
24128,bupropion,Depression,Thiruvananthapuram,December,Kozhikode
24129,sumatriptan,Migraine,Malappuram,September,Kannur
24130,darunavir,AIDS/HIV,Thrissur,June,Kasargod
24131,lidocaine viscous,Gastrointestinal,Thrissur,November,Malappuram
24132,diphenhydramine,Cold,Kozhikode,December,Aleppey
24133,bupropion,Depression,Thiruvananthapuram,July,Kasargod
24134,doxycycline,Acne,Pathanamthitta,September,Kannur
24135,lisinopril,Hypertension,Kasargod,November,Thiruvananthapuram
24136,diphenhydramine,Cold,Kozhikode,January,Kollam
24137,bupropion,Depression,Thiruvananthapuram,March,Kannur
24138,doxycycline,Acne,Pathanamthitta,January,Kasargod
24139,lidocaine viscous,Gastrointestinal,Thrissur,October,Malappuram
24140,darunavir,AIDS/HIV,Thrissur,December,Idukki
24141,eletriptan,Migraine,Wayanad,June,Idukki
24142,lisinopril,Hypertension,Idukki,February,Kannur
24143,diphenhydramine,Cold,Kannur,December,Aleppey

In [93]:
#preprocessing of data

from sklearn.preprocessing import LabelEncoder
processed_data = pd.DataFrame()

#Label Encoder converts into numerical value

lb_make = LabelEncoder()
processed_data["GENERIC NAME"] = lb_make.fit_transform(data["GENERIC NAME"])
#processed_data["GENERIC"] = data["GENERIC NAME"]
processed_data["CONDITION"] = lb_make.fit_transform(data["CONDITION"])
#processed_data["CONDITIO"] = data["CONDITION"]
processed_data["SOURCE"] = lb_make.fit_transform(data["SOURCE"])
#processed_data["src"] = data["SOURCE"]
#processed_data["cnt"] = data["COUNT"]
#processed_data["COUNT"] = lb_make.fit_transform(data["COUNT"])

processed_data["MONTH"] = lb_make.fit_transform(data["MONTH"])
#processed_data["Mon"] = data["MONTH"]
processed_data["DESTINATION"] = lb_make.fit_transform(data["DESTINATION"])
#processed_data["DESTINATIO"] = data["DESTINATION"]

In [94]:
processed_data


#pd.set_option('display.height', 2400)
#pd.set_option('display.max_rows', 2400)

       GENERIC NAME  CONDITION  SOURCE  MONTH  DESTINATION
0                15          1       1      3            2
1                18          3       7      4            3
2                13          6       4      2            1
3                 9          0       9      0            4
4                22          5      11      2           13
5                11          4      10      3            4
6                10          0       0      4           11
7                13          6       4      7           12
8                 1          3      11      4            1
9                 5          2       7      2            9
10               16          5       5      4            0
11               19          1      11      4            5
12                0          4       6      2            1
13               18          3       7     11           13
14                2          2       4      4            3
15               22          5      11      2            5
16                9          0       9      4            8
17               11          4      10     10            4
18                7          3       5      2            1
19               16          5       5      2            4
20               10          0       0      3           11
21               13          6       4      4            1
22               16          5       5      3            0
23                1          3      11      2           12
24               19          1      11      4            0
25               17          7       9      4            3
26                9          0       9      9            7
27                0          4       6      4            1
28                2          2       4      2           11
29               17          7       9      3            3
...             ...        ...     ...    ...          ...
24114             4          0      12      3            7
24115            18          3       7      2           12
24116            12          4      12      4            9
24117             6          1      10      3           11
24118            20          7       8      3           11
24119            10          0       0      4            1
24120             8          7      13      2           11
24121             2          2       4      5            3
24122             6          1      10      1           11
24123            12          4      12      2            9
24124             5          2       7      4           11
24125            12          4      12      2            8
24126             4          0      12      4            7
24127            13          6       4      3            3
24128             1          3      11      2            7
24129            20          7       8     11            3
24130             4          0      12      6            4
24131            12          4      12      9            8
24132             5          2       7      2            0
24133             1          3      11      5            4
24134             6          1      10     11            3
24135            13          6       4      9           11
24136             5          2       7      4            5
24137             1          3      11      7            3
24138             6          1      10      4            4
24139            12          4      12     10            8
24140             4          0      12      2            2
24141             8          7      13      6            2
24142            13          6       2      3            3
24143             5          2       3      2            0

[24144 rows x 5 columns]

In [95]:
# to extract the features

#printing the columns

features = processed_data.columns
print(features)

Index(['GENERIC NAME', 'CONDITION', 'SOURCE', 'MONTH', 'DESTINATION'], dtype='object')

In [96]:
#printing the last column which is used to predict 

predict_class = data.columns[-1]
predict_class

'DESTINATION'

In [97]:
#print the value to be predicted

predictions = data[predict_class]
predictions

0                    Idukki
1                    Kannur
2                 Ernakulam
3                  Kasargod
4                   Wayanad
5                  Kasargod
6        Thiruvananthapuram
7                  Thrissur
8                 Ernakulam
9                  Palakkad
10                  Aleppey
11                   Kollam
12                Ernakulam
13                  Wayanad
14                   Kannur
15                   Kollam
16               Malappuram
17                 Kasargod
18                Ernakulam
19                 Kasargod
20       Thiruvananthapuram
21                Ernakulam
22                  Aleppey
23                 Thrissur
24                  Aleppey
25                   Kannur
26                Kozhikode
27                Ernakulam
28       Thiruvananthapuram
29                   Kannur
                ...
24114             Kozhikode
24115              Thrissur
24116              Palakkad
24117    Thiruvananthapuram
24118    Thiruvananthapuram
24119             Ernakulam
24120    Thiruvananthapuram
24121                Kannur
24122    Thiruvananthapuram
24123              Palakkad
24124    Thiruvananthapuram
24125            Malappuram
24126             Kozhikode
24127                Kannur
24128             Kozhikode
24129                Kannur
24130              Kasargod
24131            Malappuram
24132               Aleppey
24133              Kasargod
24134                Kannur
24135    Thiruvananthapuram
24136                Kollam
24137                Kannur
24138              Kasargod
24139            Malappuram
24140                Idukki
24141                Idukki
24142                Kannur
24143               Aleppey
Name: DESTINATION, Length: 24144, dtype: object

In [98]:
#printing the numerical values of DESTINATION to be predicted

prediction_class = processed_data["DESTINATION"]
prediction_class

0         2
1         3
2         1
3         4
4        13
5         4
6        11
7        12
8         1
9         9
10        0
11        5
12        1
13       13
14        3
15        5
16        8
17        4
18        1
19        4
20       11
21        1
22        0
23       12
24        0
25        3
26        7
27        1
28       11
29        3
         ..
24114     7
24115    12
24116     9
24117    11
24118    11
24119     1
24120    11
24121     3
24122    11
24123     9
24124    11
24125     8
24126     7
24127     3
24128     7
24129     3
24130     4
24131     8
24132     0
24133     4
24134     3
24135    11
24136     5
24137     3
24138     4
24139     8
24140     2
24141     2
24142     3
24143     0
Name: DESTINATION, Length: 24144, dtype: int64

In [99]:
features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","MONTH"]]

#    features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","MONTH"]]

#features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE"]]
features_data

       GENERIC NAME  CONDITION  SOURCE  MONTH
0                15          1       1      3
1                18          3       7      4
2                13          6       4      2
3                 9          0       9      0
4                22          5      11      2
5                11          4      10      3
6                10          0       0      4
7                13          6       4      7
8                 1          3      11      4
9                 5          2       7      2
10               16          5       5      4
11               19          1      11      4
12                0          4       6      2
13               18          3       7     11
14                2          2       4      4
15               22          5      11      2
16                9          0       9      4
17               11          4      10     10
18                7          3       5      2
19               16          5       5      2
20               10          0       0      3
21               13          6       4      4
22               16          5       5      3
23                1          3      11      2
24               19          1      11      4
25               17          7       9      4
26                9          0       9      9
27                0          4       6      4
28                2          2       4      2
29               17          7       9      3
...             ...        ...     ...    ...
24114             4          0      12      3
24115            18          3       7      2
24116            12          4      12      4
24117             6          1      10      3
24118            20          7       8      3
24119            10          0       0      4
24120             8          7      13      2
24121             2          2       4      5
24122             6          1      10      1
24123            12          4      12      2
24124             5          2       7      4
24125            12          4      12      2
24126             4          0      12      4
24127            13          6       4      3
24128             1          3      11      2
24129            20          7       8     11
24130             4          0      12      6
24131            12          4      12      9
24132             5          2       7      2
24133             1          3      11      5
24134             6          1      10     11
24135            13          6       4      9
24136             5          2       7      4
24137             1          3      11      7
24138             6          1      10      4
24139            12          4      12     10
24140             4          0      12      2
24141             8          7      13      6
24142            13          6       2      3
24143             5          2       3      2

[24144 rows x 4 columns]

In [100]:
#training

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features_data,prediction_class,train_size = 0.80,test_size=0.20,random_state = 1)

np.random.seed(0) #to make random numbers predictable

# Show the results of the split
#print "Training set has {} samples.".format(X_train.shape[0])
#print "Testing set has {} samples.".format(X_test.shape[0])

#print(X_train.shape, y_train.shape) 
#print(X_test.shape, y_test.shape) 

print("Training samples")
print(X_train.shape[0])
#print(y_train.shape[0])
print("Testing samples")
print(X_test.shape[0])

Training samples
19315
Testing samples
4829

In [101]:
X_train

       GENERIC NAME  CONDITION  SOURCE  MONTH
8358              3          1       0      8
13906            11          4      10      4
5034             22          5      11      2
11959            14          6       8      9
21302            19          1      11      7
1390             16          5       5      2
567              19          1      11      3
8955              2          2       4      3
10774             8          7      13     10
21551             2          2       4      4
10420             4          0      12      5
13843            19          1      11      2
12142            10          0       0      0
4639             16          5       5      8
16880             3          1       0      7
11189            19          1      11      0
18034            21          1      12      8
3345              8          7      13      3
2610             13          6       4      3
16657            19          1      11      3
23655            22          5      11      2
17525             3          1       0     11
16334            22          5      11     11
1785             17          7       9      2
17422            12          4      12      4
10189             9          0       9      8
7943              2          2       4      7
22246            22          5      11      2
23770             9          0       9      8
3920             13          6       4      4
...             ...        ...     ...    ...
6285              5          2       7      0
1110              2          2       4      8
18272            13          6       4      3
11742             7          3       5      6
17137            13          6       4      2
19433            12          4      12      4
16946            20          7       8      1
22926             5          2       7     11
4764             20          7       8      4
19946             1          3      11      5
8444              1          3      11      4
18900            17          7       9      4
2962             10          0       0      7
12645            10          0       0      0
21758            19          1      11      0
21780             9          0       9      5
3462              5          2       7      5
10989            22          5      11      7
7751             20          7       8     11
16332            20          7       8      4
20609            20          7       8     11
144              19          1      11      8
21440            11          4      10      5
19279             2          2       4      6
7813              7          3       5      2
10955            18          3       7     11
17289            10          0       0      6
5192              7          3       5     11
12172            16          5       5      5
235               0          4       6      2

[19315 rows x 4 columns]

In [102]:
y_train

8358     11
13906     2
5034     13
11959    12
21302     1
1390      2
567      13
8955     12
10774     5
21551     3
10420     9
13843     5
12142    11
4639      0
16880    11
11189     5
18034    13
3345      3
2610     10
16657     5
23655     5
17525    13
16334     3
1785      7
17422     1
10189     8
7943     12
22246     4
23770     8
3920      2
         ..
6285      3
1110      3
18272     5
11742     1
17137     3
19433     1
16946    11
22926     9
4764      1
19946     1
8444     13
18900    13
2962      1
12645    11
21758     3
21780     3
3462     11
10989     7
7751     10
16332     1
20609     3
144       5
21440    11
19279     3
7813      4
10955     3
17289    11
5192     12
12172     7
235       3
Name: DESTINATION, Length: 19315, dtype: int64

In [103]:
#applying model

#fitting into KNN

from sklearn import neighbors
from sklearn.model_selection import cross_val_score

knn = neighbors.KNeighborsClassifier(n_neighbors = 3)
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [104]:
cv_scores = cross_val_score(knn, features_data, prediction_class, cv = 10)
cv_scores

array([ 0.55472945,  0.55101198,  0.54820025,  0.55730244,  0.54929577,
        0.55758078,  0.55454168,  0.55246786,  0.55126609,  0.55790785])

In [105]:
cv_scores.mean()

0.55343041425858763

In [17]:
#printing confusion matrix

knn.fit(X_train,y_train)
predictions_test = knn.predict(X_test)

predictions_test

array([ 2, 13, 11,  1,  1,  0, 10, 13,  1, 11,  3,  1,  5,  1,  3,  7, 11,
       12,  1,  2, 10,  7,  9,  8,  1, 12,  6,  0, 13, 13,  1,  0,  3,  3,
       12,  8, 13,  9,  3,  3,  1,  3,  7,  1,  1,  3,  3,  0,  3,  2,  2,
       12,  9,  0, 12,  8, 11,  1,  2,  5,  9,  8, 13,  9, 11, 11,  1,  8,
        1,  3, 11,  3,  0,  7,  7,  3,  3,  1, 11, 11,  2,  8,  1,  3, 11,
        9,  1,  3, 13,  4, 10, 12,  3,  1,  2,  9, 13,  1,  0,  3,  1,  9,
        9,  5,  1,  1,  3,  1,  3,  5,  3,  9,  9,  3,  1, 12,  1,  5,  1,
        2,  1,  9, 13,  3, 12,  1,  9,  3,  9, 13,  0,  0,  2,  3,  3,  1,
        2,  2,  5,  9,  3, 10, 11,  3, 13, 12,  9,  1,  3, 13,  1,  0,  1,
        1, 11,  3,  1, 13,  3, 13,  5,  9,  3, 11,  3,  0,  0,  1,  2,  1,
        5,  6,  1, 11,  3,  0,  5,  3,  0,  3,  3,  3,  7,  8,  0,  1,  5,
       11, 11,  1, 13, 11,  5, 12,  5,  2, 13,  3,  9,  5,  2,  8,  9,  5,
        5,  9,  3,  2, 11, 13,  1,  5, 13,  1,  1,  9,  3, 12,  9, 12,  7,
        3,  7,  3,  9,  9, 12,  3,  9,  3,  3, 11,  1, 10,  5,  1,  1,  5,
        1,  5, 11,  3,  1,  8,  2,  8,  9, 11,  2,  3, 13,  1,  5,  3,  1,
       11,  5,  1,  0, 11,  1,  5,  3,  3,  2,  7,  3,  3,  1, 11,  3,  5,
        2,  1,  1,  1,  9,  1,  1,  7, 11,  1,  1, 13, 11,  1, 12, 13,  0,
       13,  9,  1,  3,  2,  2,  1,  5, 11, 11, 11,  2,  5,  9,  2,  3,  3,
        3,  1,  3,  3, 12,  0,  3,  1,  3,  5,  1,  8, 11,  7,  0, 11,  3,
       11, 13,  1,  3,  9, 11,  2,  8,  9,  2,  9,  2,  3,  8,  8, 13,  1,
       11,  5,  9,  1,  9,  1, 13,  3,  0,  8,  1,  2,  1, 12,  1,  3,  1,
        3,  0,  2, 11,  7,  5, 13,  0,  1,  1, 11,  7,  1,  3,  9,  1,  9,
        1,  5, 11, 10,  9, 13,  3,  1,  3,  1,  9,  9,  1,  0, 11,  0,  3,
       12,  7,  1,  3,  9,  3,  3,  7,  8,  3,  7,  9,  1,  0,  1,  3,  9,
        0,  1,  1,  1,  1,  2,  5,  1,  4, 13,  5,  8,  1, 13, 11, 11, 10,
       12,  5,  3,  2,  3,  2,  7,  1,  5,  3,  1,  7, 13, 11,  5, 13,  3,
        1,  5,  1, 13,  3,  9,  1,  3,  2,  5,  1,  0, 12,  8, 11,  0, 10,
        9,  2, 13,  3,  1,  3,  7,  2, 13,  2,  3,  5, 10, 11, 11,  1,  3,
        3,  3,  0,  1,  1,  4,  3, 12,  1,  3,  3,  1, 13, 11,  8,  5,  3,
        5,  9,  5,  0, 11,  1,  5,  5,  9,  9,  1, 11, 10,  1,  3,  3,  2,
        2,  1,  2,  5, 10,  5,  1,  5, 11,  1,  3, 11,  3,  4,  2,  1,  2,
       13, 12,  8, 12,  8,  2,  1,  0,  1,  3,  3,  1,  3, 12, 10,  8,  1,
        3,  1,  1, 11, 11,  9, 12, 11,  8,  9,  9, 12,  5,  2, 11,  2,  1,
        8,  1, 11,  1,  8, 11,  9,  1,  3,  9,  3, 12,  3, 12,  3,  3,  0,
        9,  8,  7,  9,  8,  8, 11,  1, 12,  1,  3,  5,  5,  9,  1, 12, 12,
        1,  1,  3,  9,  1,  5,  2, 10, 11])

In [18]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  

# Model Accuracy: how often is the classifier correct?
print(confusion_matrix(y_test,predictions_test))

[[17  3  1  0  0  0  0  0  0  0  0  0  0  3]
 [ 0 55  3  7  0  5  2  1  0  0  1  3  0  8]
 [ 3  7 22  3  0  0  0  0  0  2  0  0  3  1]
 [ 3  8  3 56  0  0  0  0  2  3  0  5  4  3]
 [ 3  6  0  2  1  1  0  0  0  1  2  4  0  1]
 [ 1 14  0  8  0 25  0  0  0  0  2  2  2  1]
 [ 0  0  1  0  0  0  0  0  0  1  0  0  0  0]
 [ 3  4  2  4  0  6  0 10  0  1  0  0  0  0]
 [ 0  4  0  2  2  4  0  0 21  0  0  1  0  0]
 [ 0  2  4  3  0  1  0  2  0 36  0  0  0  5]
 [ 1  3  0  6  0  2  0  0  0  0  3  0  0  0]
 [ 0 10  4 10  1  3  0  4  5  4  0 38  1  4]
 [ 0  8  2  6  0  2  0  0  0  2  0  3 20  0]
 [ 1  1  2  1  0  0  0  3  0  6  5  1  0 10]]

In [19]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,predictions_test))

Accuracy is 0.519867549669

In [20]:
print(classification_report(y_test,predictions_test))

              precision    recall  f1-score   support

           0       0.53      0.71      0.61        24
           1       0.44      0.65      0.52        85
           2       0.50      0.54      0.52        41
           3       0.52      0.64      0.57        87
           4       0.25      0.05      0.08        21
           5       0.51      0.45      0.48        55
           6       0.00      0.00      0.00         2
           7       0.50      0.33      0.40        30
           8       0.75      0.62      0.68        34
           9       0.64      0.68      0.66        53
          10       0.23      0.20      0.21        15
          11       0.67      0.45      0.54        84
          12       0.67      0.47      0.55        43
          13       0.28      0.33      0.30        30

   micro avg       0.52      0.52      0.52       604
   macro avg       0.46      0.44      0.44       604
weighted avg       0.53      0.52      0.51       604

In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
#Create a Gaussian Classifier
gau = GaussianNB()

cvscores_gau = cross_val_score(gau,features_data,prediction_class,cv=10)
cvscores_gau

array([ 0.33766234,  0.31818182,  0.33114754,  0.31147541,  0.2923588 ,
        0.34883721,  0.31772575,  0.34113712,  0.30405405,  0.29391892])

In [23]:
cvscores_gau.mean()

0.31964989691800183

In [24]:
# Train the model using the training sets
gau.fit(X_train,y_train)

#Predict Output
prediction_gau = gau.predict(X_test) # 0:Overcast, 2:Mild

In [25]:
prediction_gau

array([11,  9,  3,  1,  1,  3,  5,  1,  1,  9,  5,  3,  5,  1,  8,  8, 11,
        3,  1,  3,  5, 11,  1,  8, 11,  3,  1,  9,  1,  9,  5,  3,  3,  3,
        3,  8,  9,  1,  1,  1,  8,  3,  9,  1, 11,  9,  1,  9,  5,  2,  3,
        3,  1,  9,  3,  8,  3,  9, 11,  5,  1,  8,  9,  9,  3, 11,  1,  8,
        8,  3,  8,  3,  3,  1, 11,  1,  3,  8, 11,  3,  2,  8,  1,  3,  3,
        1,  1,  1,  1,  8,  5,  3,  8,  8,  3,  1,  9,  5,  3,  5,  5,  1,
        9,  1,  8,  1,  1,  1,  8,  5,  3,  1,  9,  1,  3,  3,  8,  5,  1,
       11,  5,  9,  3,  1,  3,  9,  9,  3,  9,  3,  3,  9,  2,  9,  8,  5,
        9,  2,  5,  8,  3,  5, 11,  3,  1,  3,  9,  9,  1, 11,  1,  3,  9,
        3, 11,  3,  1,  9,  3,  3,  5,  8,  5,  3,  3,  3,  9,  3,  3,  5,
        5,  1,  3, 11,  1,  9,  5,  8,  3,  3,  3,  1,  1,  8,  3,  3,  1,
       11, 11,  1,  9, 11,  5,  3,  5,  3,  5,  1,  9,  3, 11,  8,  9,  8,
        5,  9,  1, 11, 11,  1,  1,  5,  3,  9,  9,  9,  8,  1, 11,  3, 11,
        1,  1,  1,  9,  1,  3,  5,  9,  5,  8,  3,  5,  5,  9,  1,  3,  5,
        5,  1,  5,  1,  9,  8,  3,  8,  1,  8,  2,  5,  3,  9,  5,  3,  1,
       11,  5,  5,  3, 11,  1,  8,  5,  3, 11, 11,  9,  3,  9,  3,  5,  9,
        1,  1,  8,  8,  9,  1,  1, 11,  3,  1,  3,  3,  9,  5,  3,  9,  3,
        9,  9, 11,  3,  1,  9,  5,  5, 11, 11, 11,  2,  8,  9, 11,  8,  1,
        3,  8,  8, 11,  3,  9,  1,  3,  8,  8,  3,  8, 11,  1,  3,  3,  3,
       11,  3,  3,  1,  9,  3,  3,  8,  1,  9,  8,  8,  5,  8,  8,  3,  1,
        3,  8,  9,  5,  3,  1,  1,  8,  3,  8,  1,  2,  5,  3,  1,  1,  9,
        9,  3,  1, 11,  1,  9,  9,  3,  5,  9,  8, 11,  1,  8,  1,  5,  1,
        5,  5,  5,  5, 11,  3,  1,  1,  3,  5, 11,  1,  1,  3,  9,  9,  3,
        3,  1,  5,  3,  9,  5,  9, 11,  8,  1,  9,  9,  1,  3,  1,  8,  9,
        9,  8, 11,  1,  1,  2,  8,  1,  8,  9,  5,  8,  3,  9, 11,  5,  5,
        1,  5,  9,  8,  9,  9,  9,  3,  1,  3,  1,  1,  3,  3,  5,  3,  5,
        8,  5,  1,  1,  3,  1,  9,  5, 11,  9,  3,  3,  1,  8, 11,  3,  5,
        1, 11,  3,  3,  1,  8,  1,  1,  3,  9,  1,  5,  5, 11, 11,  1,  8,
        1,  3,  9,  5,  5,  8,  3,  3,  1,  3,  1,  1,  9, 11,  8,  5,  3,
        5,  9,  5,  9,  9,  1,  5,  8,  9,  9,  1,  8,  5,  1,  3,  5,  2,
        3,  1,  2,  5,  5,  9,  1,  5,  9,  9,  5, 11,  1,  8, 11,  1,  2,
        1,  3,  8,  3,  8,  9,  1,  9,  1,  5,  8,  1,  1,  3,  5,  8,  5,
        1,  1,  1,  8,  3,  1,  3,  9,  8,  1,  9,  3,  8,  2,  9,  8,  9,
        8,  3,  8,  3,  8, 11,  8,  1,  1,  1,  8,  3,  5,  3,  3,  8,  9,
        1,  8,  9,  3,  8,  8, 11,  5,  3,  3,  3,  9,  5,  1,  1,  3,  3,
        1,  3,  1,  9,  3,  5,  3,  5, 11])

In [26]:
print(confusion_matrix(y_test,prediction_gau))

[[ 0  2  0 14  0  0  0  0  0  8  0  0  0  0]
 [ 0 38  0 15  0 13  0  0  4 10  0  5  0  0]
 [ 0  7  3  9  0  2  0  0  1  7  0 12  0  0]
 [ 0 25  3 31  0 13  0  0  7  6  0  2  0  0]
 [ 0  5  0  3  0  3  0  0  5  2  0  3  0  0]
 [ 0  3  0  9  0 29  0  0  2 10  0  2  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  0  0  0  0]
 [ 0  4  0  6  0  5  0  0  9  3  0  3  0  0]
 [ 0  0  0  0  0  2  0  0 32  0  0  0  0  0]
 [ 0 16  3  0  0  0  0  0  3 30  0  1  0  0]
 [ 0  5  0  4  0  5  0  0  0  1  0  0  0  0]
 [ 0 10  2 19  0  3  0  0 18 10  0 22  0  0]
 [ 0 15  0 22  0  4  0  0  0  0  0  2  0  0]
 [ 0  5  0  7  0  7  0  0  2  8  0  1  0  0]]

In [27]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,prediction_gau))

Accuracy is 0.306291390728

In [28]:
print(classification_report(y_test,prediction_gau))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        24
           1       0.28      0.45      0.35        85
           2       0.25      0.07      0.11        41
           3       0.22      0.36      0.27        87
           4       0.00      0.00      0.00        21
           5       0.34      0.53      0.41        55
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00        30
           8       0.39      0.94      0.55        34
           9       0.31      0.57      0.40        53
          10       0.00      0.00      0.00        15
          11       0.42      0.26      0.32        84
          12       0.00      0.00      0.00        43
          13       0.00      0.00      0.00        30

   micro avg       0.31      0.31      0.31       604
   macro avg       0.16      0.23      0.17       604
weighted avg       0.23      0.31      0.24       604

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [29]:
from sklearn import tree

dec = tree.DecisionTreeClassifier()

dec

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [30]:
cv_scores_dec = cross_val_score(dec,features_data,prediction_class,cv=10)
cv_scores_dec

array([ 0.4512987 ,  0.42207792,  0.46557377,  0.39672131,  0.4551495 ,
        0.45847176,  0.41137124,  0.45819398,  0.39189189,  0.44932432])

In [31]:
cv_scores_dec.mean()

0.43600744014098292

In [32]:
dec.fit(X_train, y_train)

prediction_dec = dec.predict(X_test)
prediction_dec

array([ 2, 13, 11,  1,  1,  7, 13, 13,  1, 11,  3,  0,  5,  1,  8,  8,  1,
       11,  1,  2, 13,  7,  9,  8,  1,  3,  6,  3,  3, 13,  5,  0, 13,  3,
        3,  8, 13,  3,  3,  3,  2,  3,  7,  1,  1,  5,  3,  3,  3,  2, 12,
        3,  3,  3, 12,  8, 11,  1,  2,  1,  9,  3, 13,  9, 11, 11,  1,  8,
        2, 12, 11,  3,  0,  1, 13, 12,  3,  1, 11, 11,  6,  8,  1,  1, 11,
        3,  1,  1, 13,  1, 13, 11,  1,  2, 12,  9, 13,  1,  7,  3,  5,  3,
        9,  9,  9, 11,  3,  1,  3,  5, 13,  9,  9,  3,  3, 12,  9,  5,  1,
        2, 12,  9,  1,  1,  3,  1,  9,  3,  9,  1,  0,  3,  6,  3,  3,  1,
        1,  6,  5, 11,  1, 13, 11,  3, 13, 12,  9,  0,  3,  5,  1,  0,  1,
        0, 11,  3,  1, 13,  3,  1,  5, 11,  3, 11,  3,  0,  3,  0,  0, 12,
        5,  6,  0, 11,  1,  3,  5,  1,  0, 12,  3,  1,  7,  8,  0,  1,  9,
       11, 11,  1, 13, 11,  5, 11,  5,  0, 11,  3,  9, 11,  2,  8,  4,  5,
        5,  9,  3,  2, 11, 13, 11,  5,  3,  1,  0,  9,  3,  1,  9, 11, 11,
       12,  7,  3,  9,  3, 12,  3,  9,  3,  8, 11,  1, 13,  5,  1,  1,  1,
        5,  9, 11,  3,  1,  8,  2,  8,  9, 11,  6,  3,  1,  0,  5, 13,  1,
       11,  5, 12,  0, 11,  1,  8,  3,  3,  2,  7,  5,  3,  0, 11,  3,  5,
        1,  1,  2,  1,  9,  1, 11, 13, 11,  1,  1,  1,  4, 12, 11, 13,  7,
       13,  9, 11, 13,  1,  1,  1,  5, 11, 11, 11,  2,  8,  9,  2,  1,  3,
       12,  2,  3,  3, 12,  3,  1,  1,  1,  8,  3,  8, 11,  7,  0, 11,  3,
       11,  1, 12,  3,  9, 11, 12,  8,  9,  9, 11, 11,  2,  8,  8,  3,  1,
       11,  8,  9,  1,  9,  1,  3,  1,  0,  8,  1,  6,  5, 12,  1,  1,  1,
        3,  0,  1, 11,  1,  5, 13,  1,  1,  0, 11,  7,  1,  8,  9, 12,  9,
        1,  5,  3, 13,  9,  3,  3,  1, 13,  5,  9,  9,  1,  0, 11,  5,  3,
       12,  7,  3,  3,  9,  3,  3, 11,  8,  3,  7,  9,  1,  7,  1,  1,  4,
        3,  9, 11,  1,  1,  6,  8,  1,  1, 13,  5,  8, 12, 13, 11, 11, 13,
        3,  8,  3, 11,  5,  9,  7,  1,  9,  3,  1,  1,  1, 11,  5,  3,  3,
        9,  5,  1, 13, 13,  3,  1,  3,  2,  5, 12,  0,  3,  3, 11,  7, 13,
        3,  2,  1, 13, 11,  8,  1,  1,  1,  1,  3,  5, 13, 11, 11,  1,  8,
        3,  3,  3,  1,  5,  1,  3, 12,  1,  1,  3,  1, 13, 11,  8,  5,  3,
        8,  9,  5,  3,  4, 12,  1,  8,  9,  9,  1, 11, 13,  1,  3,  3,  6,
        2,  1,  2,  8, 13,  6,  1,  1, 11,  0,  3,  1,  3,  1,  2,  1,  6,
       13,  3,  8,  3,  3,  9,  1,  5,  1,  2,  3,  1,  3, 12, 13,  8,  1,
       12,  1,  1, 11, 11,  3, 11, 11,  8,  9,  9, 12,  8,  6, 11, 11,  0,
        8,  1, 11,  1,  3, 11, 11,  1,  3,  3,  1, 12,  3, 12, 12,  1,  3,
        9,  8,  7,  9,  8,  8, 11,  1,  3,  3,  3,  5,  5,  9,  1, 11,  3,
       11,  1, 12,  9,  0,  5,  0, 13, 11])

In [33]:
from sklearn.metrics import accuracy_score

#confusion matrix

print(confusion_matrix(y_test,prediction_dec))

[[12  1  0  6  0  2  0  2  0  0  0  0  0  1]
 [ 4 41  1  5  0  7  2  0  0  1  0  6 10  8]
 [ 2  7 12  3  0  0  2  0  0  4  0  7  2  2]
 [ 2 11  1 52  0  5  3  0  3  0  0  5  3  2]
 [ 1  7  2  0  2  1  0  2  0  0  0  3  0  3]
 [ 4 13  0  5  0 16  1  0  4  1  0  3  4  4]
 [ 0  0  0  0  0  0  1  0  0  1  0  0  0  0]
 [ 2  6  1  4  0  3  0  4  4  2  0  3  0  1]
 [ 0  4  0  2  0  2  0  0 23  2  0  1  0  0]
 [ 0  2  0  6  1  0  3  2  1 31  0  2  0  5]
 [ 0  6  0  2  0  2  0  0  0  0  0  0  0  5]
 [ 0 14  6  8  1  1  0  3  5  4  0 38  2  2]
 [ 0 11  0 13  0  2  0  0  0  1  0  5 11  0]
 [ 1  4  0  5  0  0  0  3  0  5  0  4  0  8]]

In [34]:
#accuracy

print("Accuracy is " ,metrics.accuracy_score(y_test,prediction_dec))

Accuracy is  0.415562913907

In [37]:
#giving input 
new=pd.DataFrame([[15,1,1,3]])
new

    0  1  2  3
0  15  1  1  3

In [38]:
test=knn.predict(new)
arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
int(test)

2

In [39]:
pre_out_knn =arr[int(test)]

In [40]:
print(pre_out_knn)

Idukki

In [41]:
pre_out_gau = gau.predict(new)

In [42]:
print(pre_out_gau)

[11]

In [43]:
pre_out_dec = dec.predict(new)

In [44]:
print(pre_out_dec)

[2]